name: Cargo Publish
description: Publish package to crates.io
inputs:
  package:
    description: Which package to publish
    required: true
runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        # cargo is enough
        profile: minimal
    - name: Setup local credential
      run: cargo login ${CRATES_IO_TOKEN}
    - name: Publish package
      run: cargo publish --package ${{ inputs.package }}

