on:
  push:
    tags:
      - 'clc-engine-v*.*.*'

name: Delivery Clc Engine

jobs:
  publish-cratesio:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/cargo-publish
        with:
          package: clc-engine
        env:
          CLATES_IO_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
