on:
  push:
    tags:
      - 'clc-engine-v*.*.*'

name: Delivery Clc Engine

jobs:
  publish-cratesio:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/cargo-publish
        with:
          package: clc-engine
