name: Delivery Clcgql
on:
  push:
    tags:
      - 'clc-gql-v*.*.*'

jobs:
  push-to-ecr:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ap-northeast-1
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Setup cargo
        uses: ./.github/actions/setup

      - name: Build and push docker image to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
        run: |
          docker image build \
            --file clc-gql/.project/container/Dockerfile \
            --tag "${ECR_REGISTRY}/${ECR_REPOSITORY}:latest" .
          docker image push ${ECR_REGISTRY}/${ECR_REPOSITORY}:latest

  publish-cratesio:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/cargo-publish
        with:
          package: clc-gql
        env:
          CRATES_IO_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}

  publish-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/cache-cargo
      - name: Version
        run: |
          VERSION=$(cargo run --bin gql-version)
          echo "::set-output name=version::${VERSION}"
        id: version
      - name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./
          file: ./clc-gql/.project/container/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.actor }}/clc-gql:latest
            ghcr.io/${{ github.actor }}/clc-gql:${{ steps.version.outputs.version }}

