on:
  push:
    # for cache
    # https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#restrictions-for-accessing-a-cache
    branches: [main]
  pull_request:
    branches: [main]

name: Integration

jobs:
  build-cache:
    name: Build cache
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - name: Cargo build
        run: cargo build

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: build-cache
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - uses: ./.github/actions/install-tools
      - uses: baptiste0928/cargo-install@v1
        with:
          crate: cargo-readme
          version: latest
      - uses: baptiste0928/cargo-install@v1
        with:
          crate: cargo-sort
          version: latest
      - uses: baptiste0928/cargo-install@v1
        with:
          crate: cargo-outdated
          version: latest
      - name: Lint
        run: cargo make lint

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build-cache
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - uses: ./.github/actions/install-tools
      - uses: taiki-e/install-action@v1
        with:
          tool: "nextest"
      - name: Run Test
        run: cargo make test
        env:
          NEXTEST_PROFILE: ci


  publish-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Version
        run: |
          VERSION=$(cargo run --bin version)
          echo "::set-output name=version::${VERSION}"
        id: version
      - name: Login to ghcr.io
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./clc-cli/.project/container/Dockerfile
          push: true
          #             ghcr.io/${{ github.actor }}/clc:${{ steps.version.output.version }}
          tags: |
            ghcr.io/${{ github.actor }}/clc:latest


