on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

name: Integration

jobs:
  build-cache:
    name: Build cache
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
      - uses: ./.github/actions/cache-cargo
      - name: Cargo build
        run: cargo build
      - uses: ./.github/actions/install-tools

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: build-cache
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy
      - uses: ./.github/actions/cache-cargo
      - name: Lint
        run: cargo make lint

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build-cache
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: ./.github/actions/cache-cargo
      - name: Run Test
        run: cargo make test
        env:
          NEXTEST_PROFILE: ci
